import type { ExportResponse } from '../types'

export const fakeExport: ExportResponse = {
  count: 3,
  nextPageCursor: null,
  results: [
    {
      user_book_id: 99901,
      is_deleted: false,
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      readable_title: 'Thinking, Fast and Slow',
      category: 'books',
      source: 'Kindle',
      cover_image_url:
        'https://images-na.ssl-images-amazon.com/images/I/41shZGS-G%2BL._SL500_.jpg',
      unique_url: null,
      book_tags: [],
      document_note: null,
      summary: null,
      readwise_url: 'https://readwise.io/bookreview/99901',
      source_url: null,
      external_id: null,
      asin: 'B00555X8OA',
      highlights: [
        {
          id: 100001,
          is_deleted: false,
          text: 'Nothing in life is as important as you think it is, while you are thinking about it.',
          note: null,
          location: 42,
          location_type: 'page',
          color: 'yellow',
          highlighted_at: '2025-06-15T10:30:00Z',
          created_at: '2025-06-15T10:30:00Z',
          updated_at: '2025-06-15T10:30:00Z',
          external_id: null,
          end_location: null,
          url: null,
          book_id: 99901,
          tags: [],
          is_favorite: false,
          is_discard: false,
          readwise_url: 'https://readwise.io/open/100001',
        },
        {
          id: 100002,
          is_deleted: false,
          text: 'A reliable way to make people believe in falsehoods is frequent repetition, because familiarity is not easily distinguished from truth.',
          note: 'This explains so much about social media and misinformation.',
          location: 108,
          location_type: 'page',
          color: 'blue',
          highlighted_at: '2025-06-16T14:20:00Z',
          created_at: '2025-06-16T14:20:00Z',
          updated_at: '2025-06-16T14:20:00Z',
          external_id: null,
          end_location: null,
          url: null,
          book_id: 99901,
          tags: [],
          is_favorite: true,
          is_discard: false,
          readwise_url: 'https://readwise.io/open/100002',
        },
      ],
    },
    {
      user_book_id: 99902,
      is_deleted: false,
      title: 'How to Take Smart Notes',
      author: 'Sönke Ahrens',
      readable_title: 'How to Take Smart Notes',
      category: 'books',
      source: 'Apple Books',
      cover_image_url:
        'https://images-na.ssl-images-amazon.com/images/I/41iVa0x-0-L._SL500_.jpg',
      unique_url: null,
      book_tags: [],
      document_note: null,
      summary: null,
      readwise_url: 'https://readwise.io/bookreview/99902',
      source_url: null,
      external_id: null,
      asin: null,
      highlights: [
        {
          id: 100005,
          is_deleted: false,
          text: 'The slip-box is designed to present you with ideas you have already forgotten, allowing your brain to focus on thinking instead of remembering.',
          note: null,
          location: 78,
          location_type: 'page',
          color: 'yellow',
          highlighted_at: '2025-07-02T16:30:00Z',
          created_at: '2025-07-02T16:30:00Z',
          updated_at: '2025-07-02T16:30:00Z',
          external_id: null,
          end_location: null,
          url: null,
          book_id: 99902,
          tags: [],
          is_favorite: false,
          is_discard: false,
          readwise_url: 'https://readwise.io/open/100005',
        },
      ],
    },
  ],
}
